### ISSUE TITLE
[20pt,42pt] Implementation, training and model validation using the approach from Sidhant Gupta

### ISSUE THREAD

**Issue by ThomasKittler** [fair-acc/pulsed-power-ml#81]
SP Spent[42]: 

# Tasks: 

- [x] #64 
- [x] #68 
- [x] #70 
- [x] #69 
- [x] #71 
- [x] #62
- [x] #63
- [x] #67 
- [x] #60
- [x] #72 

# References: 
[Sidhant Gupta, "ElectriSense: Single-Point Sensing using EMI for Electrical Event
Detection and Classification [..]",PhD thesis, U-Washington, 2014](http://hdl.handle.net/1773/26334)

**Comment by mariahirsch** [comment]
Labelling training data more difficult than anticipated: there is no threshold value for peaks in Apparent Power Spectra that works as a switch detection for all appliances. Even the sum of the individual spectrum of a single time step is not comparable, although switches are clearly to be seen. 

This are the sums of a time series of switches of a blow dryer:



![Image](https://user-images.githubusercontent.com/116064210/203318842-7fa172b7-a7db-4bdb-8e1f-df7c146a125a.png)



And the sums of a time series of switches of an LED bulb:



![Image](https://user-images.githubusercontent.com/116064210/203319630-24c7a3ff-d0d3-4f69-b730-39f8b783442e.png)


Note the difference on the y axis.

**Comment by mariahirsch** [comment]
New approach: norm spectra before switch detection via sum of spectrum. Examples: 

LED bulb:

![Image](https://user-images.githubusercontent.com/116064210/203346184-75c722d2-f96d-4292-aa95-db2625d65a48.png)


or 

blow dryer:

![Image](https://user-images.githubusercontent.com/116064210/203346267-138e4881-202a-4a38-a25b-a0d72874271f.png)



For switch detection: Once any switch event is detected for a normed, background subtracted spectrum, the detection of the switch  direction (on or off) is preferrably done with the <switching_offset>th next spectrum. This approach is more robust against peaks resulting from mechanical switches.
